apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: 988772184836.dkr.ecr.ap-south-1.amazonaws.com/issue-finder:order-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
      imagePullSecrets:
      - name: cr-credentials

