apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: 988772184836.dkr.ecr.ap-south-1.amazonaws.com/issue-finder:payment-svc
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: cr-credentials
