apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: payment-service
        image: 988772184836.dkr.ecr.ap-south-1.amazonaws.com/issue-finder:user-service
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: cr-credentials
